### ISSUE TITLE
Suggestion: Use reactphp/http for http server

### ISSUE THREAD

**Issue by ging-dev** [luzrain/phprunner#2]
Using `reactphp/http` can significantly reduce the amount of code that needs to be written.

**Comment by luzrain** [comment]
Thank you for your suggestion!
The main idea of this tool is to be lightweight and fast. The HTTP server implementation itself is actually not that big compared to all the code included in the suggested library and its dependencies.
Unfortunately, I can't use it here because reactphp/http runs on top of the reactphp event loop implementation and is coupled with other reactphp components. I'm using the revolt event loop here.
